import { StyleSheet, Font } from "@react-pdf/renderer";

Font.register({
    family: "Open Sans",
    src: "http://fonts.gstatic.com/s/opensans/v13/IgZJs4-7SA1XX_edsoXWog.ttf",
    fontStyle: "normal",
    fonts: [
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTS3USBnSvpkopQaUR-2r7iU.ttf",
            fontWeight: 300,
        },
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/PRmiXeptR36kaC0GEAetxi9-WlPSxbfiI49GsXo3q0g.ttf",
            fontStyle: "italic",
            fontWeight: 400,
        },
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/IgZJs4-7SA1XX_edsoXWog.ttf",
            fontWeight: 400,
        },
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/MTP_ySUJH_bn48VBG8sNSi3USBnSvpkopQaUR-2r7iU.ttf",
            fontWeight: 600,
        },
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzC3USBnSvpkopQaUR-2r7iU.ttf",
            fontWeight: 700,
        },
        {
            src: "http://fonts.gstatic.com/s/opensans/v13/EInbV5DfGHOiMmvb1Xr-hi3USBnSvpkopQaUR-2r7iU.ttf",
            fontWeight: 900,
        },
    ],
});

const spacing = {
    m8: { marginLeft: 8, marginRight: 8, marginTop: 8, marginBottom: 8 },
    m16: { marginLeft: 16, marginRight: 16, marginTop: 16, marginBottom: 16 },
    m24: { marginLeft: 24, marginRight: 24, marginTop: 24, marginBottom: 24 },
    m32: { marginLeft: 32, marginRight: 24, marginTop: 24, marginBottom: 24 },

    p8: { paddingLeft: 8, paddingRight: 8, paddingTop: 8, paddingBottom: 8 },
    p16: {
        paddingLeft: 16,
        paddingRight: 16,
        paddingTop: 16,
        paddingBottom: 16,
    },
    p24: {
        paddingLeft: 24,
        paddingRight: 24,
        paddingTop: 24,
        paddingBottom: 24,
    },
    p32: {
        paddingLeft: 32,
        paddingRight: 32,
        paddingTop: 32,
        paddingBottom: 32,
    },

    mt8: { marginTop: 8 },
    mt16: { marginTop: 16 },
    mt24: { marginTop: 24 },
    mt32: { marginTop: 32 },
    mb8: { marginBottom: 8 },
    mb4: { marginBottom: 4 },
    mb16: { marginBottom: 16 },
    mb24: { marginBottom: 24 },
    mb32: { marginBottom: 32 },
    ml8: { marginLeft: 8 },
    ml16: { marginLeft: 16 },
    ml24: { marginLeft: 24 },
    ml32: { marginLeft: 32 },
    mr8: { marginRight: 8 },
    mr16: { marginRight: 16 },
    mr24: { marginRight: 24 },
    mr32: { marginRight: 32 },

    pt4: { paddingTop: 4 },
    pt8: { paddingTop: 8 },
    pt16: { paddingTop: 16 },
    pt24: { paddingTop: 24 },
    pt32: { paddingTop: 32 },
    pb8: { paddingBottom: 8 },
    pb16: { paddingBottom: 16 },
    pb24: { paddingBottom: 24 },
    pb32: { paddingBottom: 32 },
    pl4: { paddingLeft: 4 },
    pl8: { paddingLeft: 8 },
    pl16: { paddingLeft: 16 },
    pl24: { paddingLeft: 24 },
    pl32: { paddingLeft: 32 },
    pr4: { paddingRight: 4 },
    pr8: { paddingRight: 8 },
    pr16: { paddingRight: 16 },
    pr24: { paddingRight: 24 },
    pr32: { paddingRight: 32 },
};

export const colors = {
    gray: "#d9d9d9",
    darkGray: "#363636",
    // success: "#385623",
    success: "#4caf50",
    successMain: "#2e7d32",
    warning: "#ff9800",
    warningMain: "#ed6c02",
    // error: "#c00000",
    errorMain: "#d32f2f",
    error: "#ef5350",
    mute: "#edeff1",
    primary: "#788ec7",
    offPrimary: "#d9e2f3",
    secondary: "#00B8D9",
};

const colorStyles = {
    success: { color: colors.success },
    warning: { color: colors.warning },
    error: { color: colors.error },
    textWhite: { color: "#ffffff" },
    textGray: { color: colors.gray },
    textMute: { color: colors.mute },
    textSecondary: { color: colors.secondary },

    bgSuccess: { backgroundColor: colors.success, color: "#ffffff" },
    bgGray: { backgroundColor: colors.gray, color: "#0a0a0a" },
    bgWarning: { backgroundColor: colors.warning, color: "#ffffff" },
    bgError: { backgroundColor: colors.error, color: "#ffffff" },
    bgMute: { backgroundColor: colors.mute, color: "#0a0a0a" },
    bgPrimary: { backgroundColor: colors.primary, color: "#0a0a0a" },
    bgOffPrimary: { backgroundColor: colors.offPrimary, color: "#0a0a0a" },
};

const styles = StyleSheet.create({
    ...spacing,
    ...colorStyles,
    page: {
        padding: "6px 12px 30px 12px",
        fontSize: 9,
        lineHeight: 1.4,
        fontFamily: "Open Sans",
        fontWeight: 500,
        backgroundColor: "#fff",
        color: "#0a0a0a",
    },
    bt: { borderTop: "1px solid #0a0a0a" },
    bm: { borderBottom: "1px solid #0a0a0a" },
    bl: { borderLeft: "1px solid #0a0a0a" },
    br: { borderRight: "1px solid #0a0a0a" },
    border: { border: "1px solid #0a0a0a" },
    bt0: { borderTop: 0, borderTopWidth: 0 },
    bm0: { borderBottom: 0, borderBottomWborderTopWidth: 0 },
    bl0: { borderLeft: 0, borderLeftWborderTopWidth: 0 },
    br0: { borderRight: 0, borderRightWborderTopWidth: 0 },
    w1: { width: "100%" },
    col4: { width: "25%" },
    col3: { width: "33.333%" },
    col8: { width: "75%" },
    col6: { width: "50%" },
    hidden: { display: "none" },
    overline: {
        fontSize: 8,
        marginBottom: 8,
        fontWeight: "bold",
        textTransform: "uppercase",
    },
    h2: { fontSize: 17, fontWeight: "bold", fontFamily: "Open Sans" },
    h3: { fontSize: 16, fontWeight: "bold", fontFamily: "Open Sans" },
    h4: { fontSize: 13, fontWeight: "bold", fontFamily: "Open Sans" },
    h5: { fontSize: 11, fontWeight: "bold", fontFamily: "Open Sans" },
    h6: { fontSize: 9, fontWeight: "bold", fontFamily: "Open Sans" },
    bold: {
        fontWeight: "bold",
        color: "#0a0a0a",
        fontFamily: "Open Sans",
    },
    semibold: {
        fontWeight: 600,
        color: "#0a0a0a",
        fontFamily: "Open Sans",
    },
    body1: { fontSize: 10 },
    subtitle2: {
        fontSize: 9,
        fontWeight: "bold",
        fontFamily: "Open Sans",
    },
    subtitle3: { fontSize: 9 },
    subtitle4: { fontSize: 7 },
    alignRight: { textAlign: "right" },
    textCenter: { textAlign: "center" },
    underlineText: {
        width: "100%",
        fontWeight: "bold",
        color: "#0a0a0a",
        borderBottom: "1px solid #0a0a0a",
    },
    footer: {
        left: 0,
        right: 0,
        bottom: 0,
        paddingVertical: 8,
        paddingHorizontal: 40,
        margin: "auto",
        position: "absolute",
    },
    gridContainer: { flexDirection: "row", justifyContent: "space-between" },
    flexCenter: {
        alignItems: "center",
        justifyContent: "center",
    },
    table: { display: "flex", width: "100%" },
    tableHeader: {
        width: "100%",
        borderLeft: "1px solid #0a0a0a",
        padding: 0,
        color: colors.darkGray,
    },
    tableBody: {
        width: "100%",
        borderLeft: "1px solid #0a0a0a",
        padding: 0,
        color: colors.darkGray,
    },
    tableFooter: {
        width: "100%",
        flexDirection: "row",
        padding: 0,
        backgroundColor: colors.offPrimary,
    },
    tableTotalText: {
        paddingTop: 4,
        paddingBottom: 4,
        fontSize: 7,
        fontWeight: 600,
    },
    tableRow: {
        width: "100%",
        flexDirection: "row",
        padding: 0,
    },
    tableCell: {
        borderBottom: "1px solid #0a0a0a",
        flexGrow: 0,
        minHeight: 16,
        fontSize: 6.5,
        lineHeight: 1,
    },
    tableCellText: {
        textOverflow: "ellipsis",
        paddingRight: 4,
        paddingLeft: 4,
        fontSize: 6.5,
        lineHeight: 1,
        color: "#000000",
    },
    labelOutline: {
        border: "1px solid inherit",
        borderRadius: 4,
        lineHeight: 1,
        padding: 2,
        fontSize: 7,
        fontWeight: "bold",
        fontFamily: "Open Sans",
    },
});

export default styles;
